# Home Assistant Configuration for Smart Home Project
mqtt:

sensor:
  - platform: mqtt
    name: "Smart Home Sensor"
    state_topic: "home/test"

# Example automation (optional)
input_text:
  display_text:
    name: "Display Text"
    initial: ""
    max: 32

# Use external file for scripts
script: !include scripts.yaml

# Enable YAML mode for Lovelace UI so that ui-lovelace.yaml is used
lovelace:
  mode: yaml


